language: scala

sudo: false

services:
   - docker

scala:
   - 2.11.7
   
jdk:
   - oraclejdk8


cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
  - sbt clean coverage test &&
    sbt coverageAggregate
after_success:
  - sbt "project play-dsl" coveralls
