language: scala

scala:
   - 2.11.8
   
jdk:
   - oraclejdk8


cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
  - sbt clean coverage test
  - cd example && sbt clean test

after_success:
  - sbt coverageReport coverageAggregate codacyCoverage
