---
  swagger: "2.0"
  info:
    title: "Asobu Example API"
    description: "An example for an asobu frontend"
    version: "1.0.0"
  consumes:
    - application/json
  produces:
    - application/json
